version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: 08:30
      timezone: Europe/London
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps"

