name: Build and publish

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed


jobs:
  gradle_jib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 23
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle jib command
        run: |
         ./gradlew jib \
          --image=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE_NAME }} \
         -Djib.to.auth.username=${{ vars.DOCKERHUB_USERNAME }} \
         -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
